// <auto-generated />
namespace CodingExercise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Release3ResetMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Release3ResetMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201404011822556_Release3-Reset-Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
